apiVersion: v1
kind: Secret
metadata:
  name: movie-data-db-secret
type: Opaque
data: 
  ca.crt: Y2F0OiAvY29ja3JvYWNoLWNlcnRzL2NhLmNydDogTm8gc3VjaCBmaWxlIG9yIGRpcmVjdG9yeQ0K
  client.root.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lSQU81MUlnZ1JGRWlnNkZuYmhkSkFHbVl3RFFZSktvWklodmNOQVFFTEJRQXcKS3pFU01CQUdBMVVFQ2hNSlEyOWphM0p2WVdOb01SVXdFd1lEVlFRREV3eERiMk5yY205aFkyZ2dRMEV3SGhjTgpNak14TWpJeE1qTXdNVFUzV2hjTk1qUXdNVEU1TWpNd01UVTNXakFqTVJJd0VBWURWUVFLRXdsRGIyTnJjbTloClkyZ3hEVEFMQmdOVkJBTVRCSEp2YjNRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUIKQVFEUXpESjZvUG9oMWZyVElzUjdRZmdFbDQ3VzUvNFN6UkRkUWcyZUVvNVhGWVcwckV5YXFNejJTR1dxVW9yNgoycmZ4WGQ5OTFJWW9BQ0s5OGRTVG1EWmJndmZlamNDSjNIYWhvRFNoeGxCZlN3Q0hyYW5YNjBuSEVjMm5wSU5CCnZ2NDdNNTNLMUR2enZIRktFWXhsRnNZNnVUdVRUSFRLZWpOdHp3OFpqV1dTOFgzMW5Qd3JYaTE2SWI0djZKcEEKbllCRHArZkxWZHpPN2IxTG9lUVV0dytwaUNKVUVoZDVlazRxWUhTRjB4NkFFWVBvUjlYZjNyUWo4NW44dEFEeQpEWXZ3Sit3M25MQUhaMXZyQjkrbGZPZTM1RTdXTUx1dXV3TG0wWmdRTkVwdHIzeUxGdi8vOWorM3FJSHV2QUVWClduQXBUTk9TL3ZraHVqMkNPOUpLVk5lckFnTUJBQUdqU0RCR01BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlYKSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmQmdOVkhTTUVHREFXZ0JRNlVlUHQ2UGxMSVBFVXB3eURpV25oNkUxYgp0ekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBU0FDZ08vQXVNMHc1bFdNakJXQzhhaHpHeHplYjJqZk5LWnB3Cm5NaHhQVVNGRUNhZ1NmODZtWXkzWDF0ZFdicXhzZDBrSU5ZeHVoL1dSK0V3eHRsQk1Sd1N2UmhCdWc3S2V5ZS8KNHpNWjdRVFVwcVl5bVlUNFE1N2xkbTFnejhnMjVYY0lLcllnL09ZTklVUm5YYjYwSm96ZjNHNmxqYXRnLzhubgpMbjllUDNHSFU3QnZEME9zeUhNdnVFdUdyNkk0U0xSanlzYjVnaHlia2xwcGhzN2gwV21yaVhaRmhrT1lqUGQwClNJakhyYkRkb3JES3JlL2hudU01L0J3YVQ3azZZOHRwRmRONFRrRFFBeEp6ellrWnVkM1BSYTBwaHkvdlFmUzIKYXlHS3VUTVY0am1aTm10RVdLV3FrcTUwZjFmS2J6R3FIQy9nd0pXeVZjUXpCakcwbFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  client.root.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBME13eWVxRDZJZFg2MHlMRWUwSDRCSmVPMXVmK0VzMFEzVUlObmhLT1Z4V0Z0S3hNCm1xak05a2hscWxLSyt0cTM4VjNmZmRTR0tBQWl2ZkhVazVnMlc0TDMzbzNBaWR4Mm9hQTBvY1pRWDBzQWg2MnAKMSt0Snh4SE5wNlNEUWI3K096T2R5dFE3ODd4eFNoR01aUmJHT3JrN2sweDB5bm96YmM4UEdZMWxrdkY5OVp6OApLMTR0ZWlHK0wraWFRSjJBUTZmbnkxWGN6dTI5UzZIa0ZMY1BxWWdpVkJJWGVYcE9LbUIwaGRNZWdCR0Q2RWZWCjM5NjBJL09aL0xRQThnMkw4Q2ZzTjV5d0IyZGI2d2ZmcFh6bnQrUk8xakM3cnJzQzV0R1lFRFJLYmE5OGl4Yi8KLy9ZL3Q2aUI3cndCRlZwd0tVelRrdjc1SWJvOWdqdlNTbFRYcXdJREFRQUJBb0lCQVFDbnBEdW5YOVpWRW1QMwozNE5YMzJpTjcwMjlXTGtUU1ZpUC9YZkhnZWlOSFBla1QyNldBby9GOGV6R3FzMXhpZWlFUDdXd1p0RnNEbWZXCmovTDRxZzZDdlEzY3YzMW1jdjlBMTh0S1ZGcTFtQmVOMkM1MDhUSGtSblFUZEsvNk9xb095R3Vaclh1UlA2eksKSm5yTnMxSm5WYy95ZlVHTVREODhuREhvZHpHbG54SGp5WFJ3dGs2Rk55cytXdUZUTU1DSE1nUWpEUld6d3QzeQp6Wmo0TU1GTDZKN3dRYzY2M0lXQkp0eVlwbnRxenluNVRlcW5sM2RMQ0x4a3dRTEYrRG50MDEzWHI1RmxzanNQCkluWW9PeFVqWkRvYjE1NnAxNzROREdoRTRYbUhJQmZtMUdtMTRoWWtLWHRxTVZRaWw0eUpQRGZhckdoTnpuaDgKUHhWOXZ4NkpBb0dCQU85S05rbStsMjc1WERPWmg1YllaeE1aRnRDSVYrNW9udTlWYkZ2aEtSWkpDaWNOdk5BMgpwM3FiQ21CTi9ZQ2QxVCtpdGVQNDBXaXpWRGZRS0V1Zk1scDNOTUMzT2RFbmpBRmZvUWdnM3hnM2hXSFVyY2lrCmJObFhkK2tyYmp2Sm0vS0RJRVF2K3ZyTk5mS2hlaGxyN3ZOWDg5cS9DeW16a0I2SHRtaUloenoxQW9HQkFOOWcKMy9yQkpQVDNTZHlnU0tqc3FCUDMrS1lycjh4RmNoeklxeVRDTEYzcXlpVjdDZVhJdzk1K1Z5ZkloaVRiUlVJeApLb2YreGh6dzdtOTVGUjlMOWxpaHhHU2J5T21BNThCV0tPTXc2UC8yQmZSQ2NEMklpMnBPZXhyMURjSUtkeXczCmI4Qi9Bdmg3bnZUWld4MVc2d0M3bXpod3dwcW9LSXNVT3hNZnVONGZBb0dCQUxUZTBuUWhaUk9UMXBhR0tRL2oKR040OXE1b0tSUFRIRGNONFBVU2h4ODI1ZmJ3UlRUUFE2L3pucmdzblNFTnNpZURrMnptclBKWTRYcU1sYXgvbQpBRWlUTEVPeSt6ZlYvYVNZSlA4ZzRhRExicjJJNWFid2FmcEtmQys2RFVPUjI1ZU9kOWd5c0RIYzVUYzF5VFhuCitLRGxUVVI5L1RFVE1nOXhvM1lXSktyMUFvR0FPdFJjcU1HdFpnYXFvVHhsWm5mTlhGVDJXMjB1QTNKV3QxWHkKSE9BMnB4VnEzNndqMHl5b3lUUWs2QWxicXVGRXdFWUttWDV6MXJOdFdGWmZSYnJQeWsvd1ZUN2lEdjB3Qyt1bApJUkNFak1UU2xKM2F5Wm5vZmJybG1SZm80NjIxN1NNOGYwbjBFbFVjYkFmQ2cxdWMwTGlZREtsRjEwMXFRQmEzCjZEVjJqcWtDZ1lBMzZwS1BFTklWdWJ6UWhYN05SbkZNRTNNRXc5TlhFa1RLOUFCYzF3UEpXZm1yN3FOZ01OdmsKZTFsdEtmdkVqcDZIb3N0dDd3SGd0S2xWZlBoajZ3N1RNRUNQZHNlaWFHaW0rR3ZMU0IzZG9PQzA1WEhURXhBeAoyd2tRenVlTE92cXIvSElNMXVBcTJSeFp5VVhBVjMvT2hYYUlFR0dsNzBZYjlIRmc0S2VtSkE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

---
apiVersion: v1
kind: Service
metadata:
  name: movie-data-service
spec:
  selector:
    app: movie-data
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-data
spec:
  selector:
    matchLabels:
      app: movie-data
  replicas: 4
  template:
    metadata:
      labels:
        app: movie-data
    spec:
      initContainers:
      - name: copy-ro-scripts
        image: busybox     
        command: ["/bin/sh","-c"]
        args: 
          - cp /cockroach-readonly/cockroach-certs/* /cockroach/cockroach-certs/;
            chmod -R 640 /cockroach/cockroach-certs/;
        volumeMounts:
        - name: cockroachdb-certs
          mountPath: /cockroach-readonly/cockroach-certs/
        - name: writeable-dir 
          mountPath: /cockroach/cockroach-certs/        
      containers:
      - name: movie-data
        image: us-central1-docker.pkg.dev/sentinel-core/mov-api/mov-python:latest
        volumeMounts:
        - name: cockroachdb-certs
          mountPath: /cockroach-readonly/cockroach-certs/
        - name: writeable-dir 
          mountPath: /cockroach/cockroach-certs/  
        ports:
        - containerPort: 5000
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-login
              key: db_password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-login
              key: db_user
      volumes:
      - name: writeable-dir
        emptyDir: {}
      - name: cockroachdb-certs
        projected:
            sources:
              - secret:
                  name: my-release-cockroachdb-client-secret
                  items:
                    - key: ca.crt
                      path: ca.crt
                    - key: tls.crt
                      path: client.root.crt
                    - key: tls.key
                      path: client.root.key
